import Head from "next/head";
import Hero from "../components/hero/Hero";

// import { PrismaClient } from "@prisma/client";

// Components
import ProductKeenSlider from "../components/products/ProductKeenSlider";
import ProductKeenSliderSM from "../components/products/ProductKeenSliderSM";
import { beautyOffersData, justDropped } from "../db/ImagesDB";
import ProductKeenShowcase from "../components/products/ProductKeenShowCase";
import ProductKeenSliderTN from "../components/products/ProductKeenSliderTN";
import SliderCardTN from "../components/cards/SliderCardTN";
import LayoutOne from "../components/productFeatures/LayoutOne";
import ProductOverviewOne from "../components/productOverview/productOverviewOne";

// const prisma = new PrismaClient();

const fetchProducts = async () => {
  // const product = await prisma.
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>Faracha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-sans">
        <Hero />
        <ProductKeenSliderSM title="Chosen for you" data={justDropped} />
        <ProductKeenSliderSM
          title="Just Dropped"
          haveLabel={true}
          data={justDropped}
        />
        <ProductKeenSlider title="Beauty Offers" data={beautyOffersData} />
        <ProductKeenShowcase title="Showcase" data={beautyOffersData} />
        <ProductKeenSliderTN
          title="Selling fast"
          data={justDropped}
          bottomLine={true}
        />

        <SliderCardTN />
      </main>
    </div>
  );
}
