import Head from "next/head";
import Identification from "../components/header/Identification";
import Navigation from "../components/header/Navigation";
import UpperRibbon from "../components/header/UpperRibbon";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Faracha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <UpperRibbon />
        <Identification />
        <Navigation />
      </main>
    </div>
  );
}
